### ISSUE TITLE
blocks more responsive

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#19]
https://github.com/GregMage/xmnews/blob/9e8f54b8bad1e7923f44609493e887037dce0e0b/extra/Templates%20for%20bootstrap%204/xmnews/blocks/xmnews_block.tpl#L4

=>

`<div class="col-sm-12 col-md-6 col-lg-4 mb-3">`
or 

 `<div class="col-xs-12 col-sm-6 col-lg-4 mb-3"> `

au choix

**Comment by GregMage** [comment]
merci!
