### ISSUE TITLE
Block waiting : no display description in xs mode

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#20]
https://github.com/GregMage/xmnews/blob/bd9622d72e8b6e29990e50f2134d9de95db167d5/templates/blocks/xmnews_block_waiting.tpl#L6

From Richard :
`			<th class="d-none d-sm-table-cell" scope="col"><{$smarty.const._MA_XMNEWS_NEWS_DESC}></th>
`

et  ligne 14 : 
`<td><{$waitingnews.description|truncateHtml:50:'...'}></td>
`
en 
`<td class="d-none d-sm-table-cell"><{$waitingnews.description|truncateHtml:50:'...'}></td>
`

**Comment by alain01** [comment]
à ajouter dans la surcharge extra également

**Comment by alain01** [comment]
et `<table class="table table-striped table-hover table-sm">`

**Comment by alain01** [comment]
résumé complet : 
```
<{if $block.news != ''}>
<table class="table table-striped table-hover table-sm">
	<thead class="bg-warning">
		<tr>
			<th scope="col"><{$smarty.const._MA_XMNEWS_NEWS_TITLE}></th>
			<th class="d-none d-sm-table-cell" scope="col"><{$smarty.const._MA_XMNEWS_NEWS_DESC}></th>
			<th scope="col"><{$smarty.const._MA_XMNEWS_NEWS_USERID}></th>
			<th scope="col"><{$smarty.const._MA_XMNEWS_ACTION}></th>
		</tr>
	</thead>
	<tbody>
<{foreach item=waitingnews from=$block.news}>
	<tr>
		<td class="text-sm-center text-warning"><{$waitingnews.title}></td>
		<td class="d-none d-sm-table-cell text-warning"><{$waitingnews.description|truncateHtml:50:'...'}></td>
		<td class="text-warning"><{$waitingnews.author}></td>
		<td class="text-center">
			<a class="btn btn-outline-primary text-warning" title="<{$smarty.const._MA_XMNEWS_EDIT}>" href="<{$xoops_url}>/modules/xmnews/action.php?op=edit&amp;news_id=<{$waitingnews.id}>"><i class="fas fa-edit" aria-hidden="true"></i></a>
		</td>
	</tr>
<{/foreach}>
	</tbody>
</table>
<{else}>
	<div class="alert"><{$smarty.const._MA_XMNEWS_BLOCKS_NOWAITING}></div>
<{/if}>
```

**Comment by alain01** [comment]
J'ai enlevé le alert-warning à la fin. car s'il n-y a pas d'article en attente, autant de pas trop "flasher" l'affichage.

**Comment by alain01** [comment]
Et pour info : 
`<td class="text-sm-center text-warning"><{$waitingnews.title}></td>`

**Comment by GregMage** [comment]
Un peu trop d'infos!

Je ne vais pas changer le templates de base car c'est du bt3 et le code que tu indique est bt4. Dans extra c'est bt4 et les changement que tu demande au 2ème commentaire c'est déja le cas, du coup c'est pas hyper simple de comprendre la demande...

**Comment by GregMage** [comment]
Fixé: https://github.com/GregMage/xmnews/pull/21
