### ISSUE TITLE
Bloc carrousel

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#27]
1 - Choix des catégories (Sélection multiple)
2 - Nombre d'article
3 - Choix du type de news : 
- Top, 
- Recents, 
- Liste IDs (genre "5 8 17") (doit tout de même respecter la valeur "Nombre d'article")
4 - Choix Résumé texte (longeur / all /  0)
5 - Paramètre image : 
- Fixer la hauteur, 
- Fixer la largeur
- Mode responsive

**Comment by GregMage** [comment]
Je comprends le besoin.

Il faut les mêmes paramètres que les autres blocs: 
- Afficher les catégories (avec une entrée choix articles)
- Nombre d'articles à afficher
- Nombre de mots à afficher pour le résumé de l'article (Mettre "all" pour ne pas avoir de limite et "0" pour ne pas afficher la description)
 et en plus:
- type d'affichage: top, récent, note et aléatoire
- Choix des articles (pas par id mais par titre car plus parlant)

Pour le paramètre de l'image ce n'est pas au module de gérer ça. Au pire l'utilisateur peut faire une surcharge.

**Comment by GregMage** [comment]
intégré
