### ISSUE TITLE
Ajout nb lecture dans la page admin

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#28]
/modules/xmnews/admin/news.php

Afficher cette information sur le tableau récapitulatif dans une colonne "Nombre de lecture"
(Comme cela est fait sur le module xmdoc).

**Comment by GregMage** [comment]
Ajouté: https://github.com/GregMage/xmnews/commit/3cb55ad56a33a1143f4678e2e26c08e8fcdb78f7
