### ISSUE TITLE
Article suivant / précédent

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#29]
Possibilité d'activer 2 types de flèches depuis la page d'un article  :

- Article suivant / Article précédent (date)
- Article suivant / Article précédent de la même catégorie (date)

**Comment by GregMage** [comment]
Intéressant, pourquoi les deux possibilités?

**Comment by alain01** [comment]
Si on veut rester sur les articles qui nous intéressent, à savoir ceux de la même catégorie

Certains webmasters voudront  peut-être un lien vers les articles précédents, suivants, sans se soucier de la catégorie

Il peut donc y avoir les 2 à la fois

0 - Aucun
1 - Article suivant / Article précédent (date) toutes catégories confondues
2 - Article suivant / Article précédent (date) de la même catégorie que l'article consulté
3 - 1 + 2

**Comment by GregMage** [comment]
sympa par contre l'option 3 n'est pas intéressante. Donc 0, 1 et 2.

**Comment by GregMage** [comment]
Ajouté: https://github.com/GregMage/xmnews/commit/e9ca099bcd8238bc33a8d0b519fe9998ef69d597
