### ISSUE TITLE
Demande : bloc liste

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#35]
Demande d'ajout d'un bloc qui liste les titres des news dans un seul bloc
Option : 
1- choix de la catégorie : (liste multi sélection)
- Tout
- cat 1
- cat 2 
-  ...

2 - Longueur du titre
- Tout
- longueur fixe
- autoreglage 

3 - Images en icone
Ajouter l'image des news : Oui / NON

**Comment by GregMage** [comment]
C'est quoi l'option "autoreglage"?

**Comment by alain01** [comment]
En BT4 c'est text-truncate

**Comment by GregMage** [comment]
ta demande est compliquée, car il y a aussi le tri (par date, hits, etc). Donc on multiplie les blocs...

**Comment by GregMage** [comment]
il faut faire des choix. je ne proposerai pas l'option 2 comme présenté (complet ou nombre de mots uniquement)

**Comment by alain01** [comment]
Ok, ce qui prime d'abord, c'est le choix des catégories (multichoix)
Ensuite, 
choix du tri : les plus vus, les plus récent, les mieux notés

**Comment by GregMage** [comment]
intégré
