### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by mambax7** [GregMage/xmnews#41]
I'm getting these errors when using xswitch4, PHP 8, and the latest XOOPS 2.5.11:

`
Warning: Constant _MA_XMNEWS_INDEXCONFIG_XMSOCIAL_WARNINGNOTINSTALLED already defined in file /modules/xmnews/language/english/main.php line 66
Warning: Constant _MA_XMNEWS_INDEXCONFIG_XMSOCIAL_WARNINGNOTACTIVATE already defined in file /modules/xmnews/language/english/main.php line 67
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 32
Warning: Undefined variable $limit in file /modules/xmnews/blocks/xmnews_blocks.php line 146
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 170
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 32
Warning: Undefined variable $limit in file /modules/xmnews/blocks/xmnews_blocks.php line 146
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 170
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 32
Warning: Undefined variable $limit in file /modules/xmnews/blocks/xmnews_blocks.php line 146
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 170
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 32
Warning: Undefined variable $limit in file /modules/xmnews/blocks/xmnews_blocks.php line 146
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 170
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key 4 in file /modules/xmnews/blocks/xmnews_blocks.php line 218
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "full" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 10
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 67
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 69
Warning: Undefined array key "desclenght" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%18^187^187CF7DB%%db%3Axmnews_block.tpl.php line 70
Warning: Undefined array key "news" in file /xoops_data/caches/smarty_compile/9a9d2d7e-xmnews-xswatch4-default^%%40^40F^40FCBBA1%%db%3Axmnews_block_waiting.tpl.php line 5
`

**Comment by GregMage** [comment]
Hi,

This is normal, the templates are not up to date in 2.5.11! You have to do the update manually: 

https://github.com/GregMage/xmnews/tree/master/extra/Templates%20for%20bootstrap%204/xmnews

I will be offering an update to 2.5.11 in a few days (I am updating all my modules). To test, just copy the templates from the folder.
