### ISSUE TITLE
Pages statistiques

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#42]
Bonjour,

pourquoi ne pas avoir dans la partie admin une page de stats ?

**Paramètres d'affichage** : nb de lignes à afficher pour chaque partie (par défaut : 10 )
**Type d'affichage** : les plus  ou  les moins

Note sur les  +/- : 
"+" : cela permet de voir ce qui marche bien, ce qui semble plaire
"-" : cela permet de voir ce qui ne marche pas et donc les efforts à faire pour remonter ces éléments

- Par catégories :
Nb articles / nb lectures cumulées / nombre d'auteurs différents

- Articles :
Nb articles (en tout / par catégories )
Articles les plus lus (par catégories / en tout)
Articles les mieux notés (par catégories / en tout)
Articles les plus commentés

- Auteurs
les plus actifs / les plus lus / les mieux notés

**Comment by GregMage** [comment]
Un module de statistique qui englobe plusieurs modules serait plus intéressant. Peut êttre un jour...
