### ISSUE TITLE
Badge "category" on index page - cosmectic modification

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#43]
https://github.com/GregMage/xmnews/blob/0d3e002ad493cdaf8b1971053d5dbbd2a3ef3f65/extra/Templates%20for%20bootstrap%204/xmnews/xmnews_index.tpl#L44

I 've added a <br /> and a lighter font-weight for the badge and link to the category : 

`								<h5 class="mb-0 text-white"><{$news.title}><{if $news_cid == 0}><br /><a href="index.php?news_cid=<{$news.cid}>"><span class="badge badge-pill badge-dark" style="font-weight: lighter;" ><{$news.cat_name}></span><{/if}></a></h5>
`

**Comment by alain01** [comment]
Visible on https://www.monxoops.fr/modules/xmnews/ ;-)

**Comment by GregMage** [comment]
Merci Alain!

C'est ok: https://github.com/GregMage/xmnews/commit/7585fa85312dc1d9c29c1bc5432ec376056504e7

P.S Tu peux écrire en français ;-)
