### ISSUE TITLE
PHP8

### ISSUE THREAD

**Issue by mambax7** [GregMage/xmnews#45]
In /modules/xmnews/admin/news.php

Warning: Undefined array key "news_cid_options" in file /xoops_data/caches/smarty_compile/da890def-xmnews-cp-default-default^%%A2^A29^A2910890%%db%3Axmnews_admin_news.tpl.php line 46

**Comment by GregMage** [comment]
Thanks!

Fixed: https://github.com/GregMage/xmnews/commit/e7c5823bad43999a9144b16854ac0e59e74da056
