### ISSUE TITLE
plugin tag

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#49]
Lien d'aide pour construire le plugin tag : 
https://github.com/XoopsModules25x/tag/blob/master/language/english/help/plugin_dev.tpl

"You can do it already with the Tag module, by adding the tags “A1”, “Tennis” or “A2” and “Basketball” to an article, and then users can check for their topics of interest in the Tag module directly. "

**Comment by alain01** [comment]
![Capture d’écran 2021-11-29 221022](https://user-images.githubusercontent.com/5336960/143943811-fa6192e7-2ad0-4769-bb24-8579979bd7ee.png)
![Capture d’écran 2021-11-29 221045](https://user-images.githubusercontent.com/5336960/143943814-db43602a-d3ea-4cdc-aac0-b766305d604d.png)
![Capture d’écran 2021-11-29 221144](https://user-images.githubusercontent.com/5336960/143943815-4d6a27c9-2763-43fb-a9cc-d57734e005e1.png)

**Comment by GregMage** [comment]
Intégré
