### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by cesagonchu** [GregMage/xmnews#5]
Merci pour ce module ;-)

J'ai commencé à tester et, sans avoir créé encore quoi que ce soit, juste après l'installation, en allant à l'onglet "Permissions" côté admin, j'ai ces erreurs :

ERRORS
Notice: Undefined variable: tab_perm in file /modules/xmnews/admin/permission.php line 42
Warning: array_keys() expects parameter 1 to be array, null given in file /modules/xmnews/admin/permission.php line 42
Warning: Invalid argument supplied for foreach() in file /modules/xmnews/admin/permission.php line 42
Notice: Undefined variable: global_perms_array in file /modules/xmnews/admin/permission.php line 95
Warning: Invalid argument supplied for foreach() in file /modules/xmnews/admin/permission.php line 95
Notice: Undefined offset: 0 in file /class/xoopsform/grouppermform.php line 268
Warning: Invalid argument supplied for foreach() in file /class/xoopsform/grouppermform.php line 268

Mon Xoops et le module sont installés en anglais.

**Voici ma config :**
Configuration Check
Minimum PHP required: 7.0 (your version is 7.3.13-1+ubuntu16.04.1+deb.sury.org+1) 
MYSQL Minimum version required: 5.5 (your version is 5.7.28-0ubuntu0.16.04.2)
Minimum XOOPS required: 2.5.10 (your version is 2.5.11-Alpha1) 
Minimum SYSTEM module version required: 2.12 (your version is 2.15)
Minimum XMDOC module version required: 0.5 (your version is 0.5)
The folder '/WEB/xxxx/www/uploads/xmnews/images/' exists 
The folder '/WEB/xxxx/www/uploads/xmnews/images/' must be with a chmod '777' (it's now set on 777). 
Server status
Information taken from PHP ini file:
Server uploads status: ON
Max upload size permitted (upload_max_filesize directive in php.ini): 2M
Max post size permitted (post_max_size directive in php.ini): 8M
Memory limit (memory_limit directive in php.ini): 128M

**Comment by GregMage** [comment]
Salut,

Merci pour ton retour, il faut créer une catégorie pour voir les permissions. Je vais changer le code pour éviter ce problème.

Merci pour ton retour!
