### ISSUE TITLE
Image catégorie

### ISSUE THREAD

**Issue by cesagonchu** [GregMage/xmnews#6]
Lorsque l'on souhaite créer une "news" côté utilisateur, l'image par défaut de la catégorie est inexistante.

![imgcat](https://user-images.githubusercontent.com/4613970/71549156-fc30cf80-29b8-11ea-86f9-1d7f04998921.png)

**Comment by GregMage** [comment]
Salut,
Mes modules ne sont pas compatibles avec ce thème...Il faut un thème bootstrap pour pouvoir les utiliser.
Le problème vient probablement de là.
