### ISSUE TITLE
Changement de catégorie

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#8]
Hello,
pas facile à expliquer.
pour un article existant,
si on veut changer cet article de catégorie,
l'image proposé est soit "Blank", soit celle de la catégorie initiale, uniquement.
Il faut valider la news avec la nouvelle catégorie puis à nous veau l'éditer pour changer l'image de la catégorie.

Symptôme quasi identique quand pour une catégorie, on change l'image en changeant le nom de l'image,
un article de la catégorie garde l'ancienne image
donc c'est lourd quand il y aura des dizaines d'articles

Pas facile à expliquer/comprendre, je pourrais l'expliquer en mode démo si besoin...

**Comment by GregMage** [comment]
Salut,

J'ai bien compris ton explication. L'image de l'article est proposée par défaut lors de la création de l'article et reprend l'image de la catégorie. Si tu change de catégorie il n'y a aucune raison de changer l'image de l'article (c'est une proposition par défaut, si elle te convient tu la laisse sinon tu mets une image perso pour la news. Tu change de catégorie, on ne doit pas changer l'image!). Ta demande au départ était de proposer une image par défaut. Donc c'est un comportement normal. J'étais pas fan d'implémenter cette possibilité au départ à cause de ce genre de chose. Il faudra vivre avec cette effet...

**Comment by alain01** [comment]
Haaa, ce n'est pas l'image de la catégorie, mais l'image de la news ?
Je comprends alors le comportement.
il faut que je regarde mieux l'édition de l'image pour voir si on peut changer, si le système propose d'autres images dans la liste des images des news et non des catégories.

PS : dans ce cas, l'ajout du lien vers la catégorie, que j'ai faîtes ne va pas...
