### ISSUE TITLE
Description catégorie

### ISSUE THREAD

**Issue by alain01** [GregMage/xmnews#9]
Hello,
page /modules/xmnews/admin/category.php?op=edit&category_id
La description prends en compte les retours à la ligne,
quand on revient sur la page /modules/xmnews/admin/category.php,
la colonne description affiche le texte à la suite sans retour à la ligne

**Comment by alain01** [comment]
Et dans la colonne de description, la mise en forme donnée dans la page de la catégorie n'est pas reprise.
EX :

>[b]CS[/b] : [b]C[/b]atégorie [b]S[/b]péciale
Cette catégorie permet d'effectuer des essais d'affichage pour le groupe des rédacteurs.
Elle n'est pas visible par des membres standards.

devient dans la liste des catégories : 

> CS Catégorie SpécialeCette catégorie permet d'effectuer des essais d'affichage pour le groupe des rédacteurs.Elle n'est pas visible par des membres standards.

Plus de mise en forme, plus de ":".

**Comment by GregMage** [comment]
Salut, c'est le comportement souhaité. Je ne veux pas que la description prenne trop de place en admin. Ça donne une indication sur le contenu.

**Comment by alain01** [comment]
Humm,
Vu qu'il y a souvent une image, la hauteur de l'image est bien + importante que la zone de description de la catégorie.
Ok pour la mise en forme, on ne la remet pas, mais pour les retours chariots, ça fait un peu bizarre, non ?
